wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1684659447.841788
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 54
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 54
      - 55
      - 80
      3:
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 4
loss:
  desc: null
  value: energy
learning_rate:
  desc: null
  value: 0.001
val_percent:
  desc: null
  value: 0.25
save_checkpoint:
  desc: null
  value: false
amp:
  desc: null
  value: true
